/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './auth.module';
import * as i2 from './signup.component.ngfactory';
import * as i3 from './signin.component.ngfactory';
import * as i4 from './logout.component.ngfactory';
import * as i5 from '@angular/common';
import * as i6 from '@angular/forms';
import * as i7 from './auth.service';
import * as i8 from '@angular/http';
import * as i9 from '../errors/error.service';
import * as i10 from '@angular/router';
import * as i11 from './signup.component';
import * as i12 from './signin.component';
import * as i13 from './logout.component';
export const AuthModuleNgFactory:i0.NgModuleFactory<i1.AuthModule> = i0.ɵcmf(i1.AuthModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.SignupComponentNgFactory,i3.SigninComponentNgFactory,i4.LogoutComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i5.NgLocalization,
          i5.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i6.FormBuilder,i6.FormBuilder,
          ([] as any[])),i0.ɵmpd(4608,i6.ɵi,i6.ɵi,([] as any[])),i0.ɵmpd(4608,i7.AuthService,
          i7.AuthService,[i8.Http,i9.ErrorService]),i0.ɵmpd(512,i5.CommonModule,i5.CommonModule,
          ([] as any[])),i0.ɵmpd(512,i6.ɵba,i6.ɵba,([] as any[])),i0.ɵmpd(512,i6.ReactiveFormsModule,
          i6.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i10.RouterModule,i10.RouterModule,
          [[2,i10.ɵa],[2,i10.Router]]),i0.ɵmpd(512,i1.AuthModule,i1.AuthModule,([] as any[])),
          i0.ɵmpd(1024,i10.ROUTES,() => {
            return [[{path:'',redirectTo:'signup',pathMatch:'full'},{path:'signup',
                component:i11.SignupComponent},{path:'signin',component:i12.SigninComponent},
                {path:'logout',component:i13.LogoutComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdmFkaW1zL2RlbW8vbWVhbmFwcDAwMS9hc3NldHMvYXBwL2F1dGgvYXV0aC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvdmFkaW1zL2RlbW8vbWVhbmFwcDAwMS9hc3NldHMvYXBwL2F1dGgvYXV0aC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
